[tool]
[tool.poetry]
name = "stringpod"
version = "0.1.0"
homepage = "https://github.com/jyyyeung/stringpod"
description = "Matching texts across languages."
authors = ["Jasmine Yeung <yeungjyy@gmail.com>"]
readme = "README.md"
license = "MIT"
classifiers = [
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.12',
]
packages = [{ include = "stringpod" }, { include = "tests", format = "sdist" }]

[tool.poetry.dependencies]
python = ">=3.12.3,<4.0"
click = "8.0.1"

black = { version = "^25.1.0", optional = true }
isort = { version = "^6.0.0", optional = true }
flake8 = { extras = ["docstrings"], version = "^7.1.2", optional = true }
flake8-docstrings = { version = "^1.6.0", optional = true }
mypy = { version = "^1.15.0", optional = true }
pytest = { version = "^8.3.4", optional = true }
pytest-cov = { version = "^6.0.0", optional = true }
tox = { version = "^4.24.1", optional = true }
virtualenv = { version = "^20.2.2", optional = true }
pip = { version = "^23.0", optional = true }
mkdocs = { version = "^1.6.1", optional = true }
mkdocs-include-markdown-plugin = { version = "^1.0.0", optional = true }
mkdocs-material = { version = "^9.6.5", optional = true }
mkdocstrings = { version = "^0.28.1", optional = true }
twine = { version = "^6.1.0", optional = true }
mkdocs-autorefs = { version = "^1.3.1", optional = true }
pre-commit = { version = "^4.1.0", optional = true }
toml = { version = "^0.10.2", optional = true }
bump2version = { version = "^1.0.1", optional = true }
opencc = "^1.1.9"
hanzidentifier = "^1.3.0"
mkdocstrings-python = { version = "^1.16.1", optional = true }

[tool.poetry.extras]
test = [
    "pytest",
    "black",
    "isort",
    "mypy",
    "flake8",
    "flake8-docstrings",
    "pytest-cov",
]

dev = [
    "tox",
    "pre-commit",
    "virtualenv",
    "pip",
    "twine",
    "toml",
    "bump2version",
]

doc = [
    "mkdocs",
    "mkdocs-include-markdown-plugin",
    "mkdocs-material",
    "mkdocstrings",
    "mkdocs-autorefs",
    "mkdocstrings-python",
]

[tool.poetry.scripts]
stringpod = 'stringpod.cli:main'

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
skip_gitignore = true
# you can skip files as below
#skip_glob = docs/conf.py

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
